### ISSUE TITLE
Fail to start script with helm vault

### ISSUE THREAD

**Issue by acherifi** [Just-Insane/helm-vault#14]
## Describe the bug

When starting the script, I got an error when trying to compare the OS to windows string.

`/home/acherifi/.local/share/helm/plugins/helm-vault/src/vault.py:192: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if platform.system() is not "Windows":
`

## To Reproduce

- Install via helm plugin install
- Try to start via helm vault

## Expected behavior

The help of the helm vault plugin should be shown

## Environment:

 * OS: Ubuntu 20.04
 * Python Version; 3.8
 * Vault Version latest

**Comment by Just-Insane** [comment]
Appears to be a new warning in Python 8.5+, and the solution would be to change "is not" to "!=" as done in the PR on your fork.

**Comment by Just-Insane** [comment]
Fixed in release v0.2.2
