### ISSUE TITLE
Helm plugin does not work but cloned repo does

### ISSUE THREAD

**Issue by acherifi** [Just-Insane/helm-vault#18]
## Describe the bug

When trying to use the helm plugin, an error always occur when trying to encrypt/decrypt a file.
However doing the same operations from the cloned repo works.

## To Reproduce

1. Install the helm plugin
2. Set the VAULT_ADDR and VAULT_TOKEN env variables
3. Try to encrypt a file with helm vault enc
4. Error shows up printing the current work dir

## Expected behavior

Register credentials to the precised vault instance

## Environment:

 * OS: Ubuntu 20.04
 * Python Version 3.8
 * Vault Version Latest

**Comment by crimv42** [comment]
I too have this problem. I find if i run the command from inside the plugin directory, it works. It appears as if the plugin is looking for a file relative to the path of plugin, and not able to complete the operation.

**Comment by Just-Insane** [comment]
Looking into this now. I don’t see anything obvious within the source that would cause this.

**Comment by crimv42** [comment]
Thanks for looking!

Here is an example of what im doing, and the error.

Install Helm and Plugin to docker image using:
```
# Install Helm for template parsing
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
# Install Vault Helm plugin
RUN pip3 install ruamel.yaml hvac GitPython
RUN pip3 install git+https://github.com/Just-Insane/helm-vault
RUN helm plugin install https://github.com/Just-Insane/helm-vault
```
Then when I have a file at `/test.yaml` and run:
`helm vault dec /test.yaml`
in that directory, I get the following:

```
bash-5.0# helm vault dec /test.yaml 
/root/.local/share/helm/plugins/helm-vault/src/vault.py:192: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if platform.system() is not "Windows":
ERROR: /
bash-5.0# pwd
/
```

Running the same command in `/root/.local/share/helm/plugins/helm-vault`

```
bash-5.0# pwd
/root/.local/share/helm/plugins/helm-vault
bash-5.0# helm vault dec /test.yaml 
/root/.local/share/helm/plugins/helm-vault/src/vault.py:192: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if platform.system() is not "Windows":
Done Decrypting
```

It decrypts without issue.

**Comment by Just-Insane** [comment]
Interesting. Is there a specific reason you are running `helm vault dec /test.yaml` rather than `helm vault dec test.yaml`?

Running with a leading `/` is likely to cause issues on this line I think: https://github.com/Just-Insane/helm-vault/blob/538f41c49a18dd80b4c6521e3f57fd3e2552e501/src/vault.py#L348

**Comment by crimv42** [comment]
Either way does the same

**Comment by crimv42** [comment]
```
bash-5.0# helm vault dec test.yaml 
/root/.local/share/helm/plugins/helm-vault/src/vault.py:192: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if platform.system() is not "Windows":
ERROR: /
bash-5.0# pwd
/
```

**Comment by Just-Insane** [comment]
I am able to reproduce the issue on my end.

**Comment by Just-Insane** [comment]
@crimv42 can you try replacing `vault.py` in `helm/plugins/helm-vault/src` with this version? https://gist.github.com/Just-Insane/0920cea440afd5a49402e275771def04

There is some weirdness going on on lines 223-224, I don't recall what that Git stuff is for, but removing it seems to resolve the problem.

 https://github.com/Just-Insane/helm-vault/blob/538f41c49a18dd80b4c6521e3f57fd3e2552e501/src/vault.py#L223-L224

``` 
        #self.folder = Git(os.getcwd())
        #self.folder = self.folder.get_git_root()
        self.folder = os.getcwd()
```

that gist has some extra debug lines that I'll remove before pushing out a fix.

**Comment by Just-Insane** [comment]
Nevermind, that is not going to work. It's been a while since I looked at/used this program, but if that is not there, it uses the current working directory as the path within Vault, which causes problems if you try and decrypt from a different machine, or from a different cwd on the same machine.

**Comment by Just-Insane** [comment]
So, the problem is that it is looking for a git repo either at the same level, or at some level above the current working directory.

If you were to cd into a git repo, and then run `helm vault dec /test.yaml` it should work as expected.

As for how to resolve the issue going forward, I'm not 100% sure. I don't want there to be a requirement for having a git repo, even though most people probably are storing their yaml config files in git.

The alternate solution is to require [vault path templating](https://github.com/Just-Insane/helm-vault#vault-path-templating), this prevents the need to try and know what the path will be across devices by checking for a git repo.

**Comment by crimv42** [comment]
This is a great find. I confirmed after creating a test directory, and running a git init where the yaml file is, that it worked. If nothing else, this is a good work around for now.

Thanks for looking into this, and writing this plugin!

**Comment by Just-Insane** [comment]
No problem! I’m open to suggestions for better ways of handling the path within Vault. Maybe based on information already stored in the yaml?

Only issue I could see with that is that this isn’t necessarily just for helm values files, so expecting anything standard there wouldn’t work.

Another thought might be to hash the keys of the values being “encrypted”, but that would make it nearly impossible to change the file without re-entering all of the values, and it would have to be computed before asking the user for input.

I think adding a check for a git repo and then erroring if one is not found and vault path templating is not set up might be the best route. I’ll take a look into that tomorrow.

**Comment by Just-Insane** [comment]
Oh, another note @crimv42, you just need to be in a folder when you run `helm vault`, the `.yaml` file can be anywhere on the system.

For example, if I `cd` into `~/testgit`, which has a `.git` folder, I can run `helm vault enc -f /values.yaml` and the path in Vault will be (by default) `secret/helm/testgit/<rest of path from values.yaml`.

The original thinking behind that was that most people stored their helm yaml files in git, and basing the path in vault off that git repo name would be a decent way of knowing which vaules you were trying to access. This could lead to path collisions though, so should probably be changed.

I'm thinking the best solution for wider usage would be to extend [Vault path templating](https://github.com/Just-Insane/helm-vault#vault-path-templating) to set the whole Vault path, that way you don't need to set `--vaultpath` across multiple machines. I'm also going to make an issue to put the envrionment variables and flags into the README.

**Comment by acherifi** [comment]
> So, the problem is that it is looking for a git repo either at the same level, or at some level above the current working directory.
> 
> If you were to cd into a git repo, and then run `helm vault dec /test.yaml` it should work as expected.
> 
> As for how to resolve the issue going forward, I'm not 100% sure. I don't want there to be a requirement for having a git repo, even though most people probably are storing their yaml config files in git.
> 
> The alternate solution is to require [vault path templating](https://github.com/Just-Insane/helm-vault#vault-path-templating), this prevents the need to try and know what the path will be across devices by checking for a git repo.

Thank you for the analysis. I was indeed doing my tests in a directory with no git repo. It will not be a problem now as the code is finally under git now.

**Comment by Just-Insane** [comment]
Thanks for the update, I'm going to leave this issue open for now with the plan to remove the git checking in a future update.
