### ISSUE TITLE
Add Mount Point customisation

### ISSUE THREAD

**Issue by asergeant01** [Just-Insane/helm-vault#4]
## Is your feature request related to a problem? Please describe.

With Vault, there is no guarantee that the mountpoint of key value secrets will be /secrets/data. That is why in hvac you have the option to use mount point.
e.g.

```
import hvac
client = hvac.Client()

client.secrets.kv.v2.configure(
    max_versions=20,
    mount_point='kv',
)
```

## Describe the solution you'd like

I would suggest adding an environment variable/param like vaultpath for mountpoint.

## Describe alternatives you've considered

N/A

## Additional context

I did fork your repo and test it out - https://github.com/asergeant01/helm-vault

**Comment by Just-Insane** [comment]
Hello, I've taken a look at your fork, and the changes look good. Can you open a pull request for that?

If you feel like opening a PR for the other changes you made, that would be awesome too!

**Comment by Just-Insane** [comment]
@asergeant01 Were you planning on opening a PR for this? If not, I will see about adding these changes myself.

**Comment by Just-Insane** [comment]
I think this was actually resolved with the introduction of [Vault Path Templating](https://github.com/Just-Insane/helm-vault#vault-path-templating) and the `SECRET_TEMPLATE` variable.

I’m going to close this for now. Feel free to re-open if you feel this is inadequate.

**Comment by asergeant01** [comment]
@Just-Insane Hi, sorry i never followed up with this.

I've just looked at the changes you've made and they definitely help but don't solve the overall issue.

HVAC works on the basic url structure `{server_ip}/v1/{mount_point}/data/{path}`

The VAULT_ADDR gets inserted to `{server_ip}`
The VAULT_PATH allows configuration of the `{path}`

The only way to change the mount_point (that i can see, i might have missed it) is to use the SECRET_TEMPLATE. This probably works well in many usecases, but in the case whereby vault has multiple namespaces and i need to reach a url in the format of - `{vault_addr}/v1/{namespace}/{mount_point}/data/{path}` - the secret template does not allow for this due to `VAULT_PATH_POSITION = 0` being hard coded.

This results in `{vault_addr}/v1/{namespace}/data/{mount_point}`.

The easiest solution would be to make VAULT_PATH_POSITION configurable.... but its probably not the most intuitive.

I might fork the current version and have a look for a better solution.

**Comment by Just-Insane** [comment]
Hey, sorry about that.

I don’t use Vault Enterprise so don’t have access to namespaces and am not really able to test this configuration.

The easiest solution might be to add a new namespace flag, then create the URL and store it in a variable, which is then called when needed.

**Comment by asergeant01** [comment]
Thats ok, i'm happy to test..... I've forked and refactored a little..... 
https://github.com/asergeant01/helm-vault/tree/mountpoint-work


This allows me now to....
```
export VAULT_MOUNT_POINT="cst/helm"
export VAULT_PATH=""
export SECRET_DELIM="lookup_vault"
export KVVERSION="v2"
```

where VAULT_MOUNT_POINT includes the namespace and the mount point.....
i override VAULT_PATH as i just want it to be inserted at the root of the mount point, but setting the path equally works....

Would you be happy to open a PR to your repository?
