### ISSUE TITLE
Exit with non-zero exit code if helm exited with non-zero code

### ISSUE THREAD

**Issue by gyrter** [Just-Insane/helm-vault#46]
## Is your feature request related to a problem? Please describe.

I'm using helm vault in CI/CD pipeline, but the lint call did not fail on error. Bad exit code suppressed by the plugin.

## Describe the solution you'd like

Exit with non-zero exit code on error. I think that catching the exit code of helm is the best solution.

## Describe alternatives you've considered

Ok, there is an alternative - the plugin can parse logs for lint calls and exit with some non-zero code on error.

**Comment by Just-Insane** [comment]
Awesome! It does make sense to pass through the helm errors.

I've reviewed your PR and merged it.
